spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://dev-db:5432/anverraglobal}
    username: ${DB_USER:devuser}
    password: ${DB_PASSWORD:devpass}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  data:
    redis:
      host: ${REDIS_HOST:dev-redis}
      port: ${REDIS_PORT:6379}
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: INFO
    com.anverraglobal: DEBUG
